import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import './styles.scss';
import Head from "next/head";
import { Providers } from "./providers";


const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Loading",
    description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>)
{

    return (
        <html lang="en">
            <Head>
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            </Head>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <div className="app">
                    <Providers>
                        { children }
                    </Providers>
                    {/* <ConfigProvider theme={{ token: { colorPrimary: '#F16018' } }}>

                        <Header />

                        <Main>
                            { children }
                        </Main>

                    </ConfigProvider> */}
                </div>
            </body>
        </html>
    );
}
