import type { Metadata } from "next";
import { Providers } from "./providers";
import "./globals.css";


export const metadata: Metadata = {
    title: {
        template: "%s - Daily Movie",
        default: 'Daily Movie'
    },
    description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>)
{

    return (
        <html lang="en">
            <head>
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            </head>
            <body className={`antialiased`}>
                <div className="app">
                    <Providers>
                        { children }
                    </Providers>
                </div>
            </body>
        </html>
    );
}
